.goreleaser.yml
Using flag `-trimpath` for `go build` could use the file name which begins with `path@version` (for go modules) instead of `absolute file system path`. It can help with reducing the build file size (and not associated with a GitHub action environment).
Reference: [pkg.go.dev/cmd/go](https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies)
It'll be 7,845,888 bytes.
It'll be 7,823,872 bytes.
=> add `-trimpath` flags to goreleaser

.github/dependabot.yml, .github/workflows/docker-image.yml, .github/workflows/release.yml
changes:
- replace the archived `crazy-max/ghaction-docker-buildx@v3` with official docker actions.
- update some GitHub Actions.
- use docker actions to make the workflow clear.
- enable dependabot to keep dependencies up-to-date.
I've tested those workflows as below ():
- https://github.com/yin1999/ddns-go/actions/runs/2261445162
- https://github.com/yin1999/ddns-go/actions/runs/2261445161
=> build(ci): update dependencies and refactor

config/domains.go, dns/alidns.go, web/writing.html
允许用户在 Domains 输入框通过以冒号分隔的形式手动设置主机记录和主域名，这对于用户只拥有子域名管理权时非常有效。
=> feat: add custom user primary domain support

dns/baidu.go
=> fix: 修复了百度云同一域名改变解析类型时失败的bug

config/config.go, util/http_client_util.go
=> fix: use tcp6 when get ipv6 from api

README.md, config/config.go, config/domains.go, config/webhook.go, dns/alidns.go, dns/baidu.go, dns/callback.go, dns/cloudflare.go, dns/dnspod.go, dns/huawei.go, dns/index.go, dns/porkbun.go, go.mod, main.go, web/basic_auth.go, web/netInterfaces.go, web/save.go, web/webhookTest.go, web/writing.go
For a published module, we should use `repo`'s url as the module path, so we can download or refer it by go module.
And for we are in v4.x, so we should add the `/v4` suffix to the module path.
<https://go.dev/doc/tutorial/create-module#start>:
> Run the go mod init command, giving it your module path -- here, use `example.com/greetings`. If you publish a module, this must be a path from which your module can be downloaded by Go tools. That would be your code's repository.
=> build: correct the module path

config/config.go, go.mod, go.sum, util/user.go
The `os.UserHomeDir` is added since [go 1.12](https://pkg.go.dev/os#UserHomeDir).
=> refactor: update dependency and use build-in function

Dockerfile, Makefile
For faster Docker multi-platform builds, see 4067132 and https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
For shrink Go binaries, see 01d392d and https://pkg.go.dev/cmd/link
=> feat: faster Docker multi-platform builds and shrink Go binaries

README.md, config/config.go, config/domains.go, config/webhook.go, dns/google_domain.go, util/http_util.go, util/huawei_signer.go, util/net.go, util/net_test.go, web/save.go, web/writing.go, web/writing.html
=> feat: add support for getting IP addr by scripts

.github/workflows/release.yml, .goreleaser.yml
GoReleaser's `--rm-dist` and `archives.replacements` has been deprecated.
See https://goreleaser.com/deprecations/#-rm-dist and https://goreleaser.com/deprecations/#archivesreplacements
=> fix: goreleaser deprecates --rm-dist and archives.replacements

Dockerfile, Makefile
If you try to run `make build_docker_image` on a machine without buildkit enabled, it will output:
```
Sending build context to Docker daemon  696.3kB
Step 1/15 : FROM --platform=$BUILDPLATFORM golang:1.19-alpine AS builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
make: *** [Makefile:18: build_docker_image] Error 1
```
Looks like it fails after #498 because it requires buildkit, add `DOCKER_BUILDKIT=1` to enable buildkit to fix this.
Also, add `--no-cache` to `apk add` to not cache the index locally, forgot to do that in #498.
=> fix(make): build_docker_image failed [skip ci]

README.md
Added `GitHub release downloads` and `Go version` Shields.
`Development environment` line has been removed due to the addition of the Go version Shield.
=> docs: add github release downloads and go version shields

.github/workflows/release.yml, .github/workflows/test.yml
Getting Go version from the `go.mod` file.
See: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file
=> chore(CI): getting Go version from the `go.mod` file

web/basic_auth.go
如配置文件为空, 超过2天禁止从公网访问页面
防止网络空间测绘
=> feat: If the configuration is empty and after two days, access to the web from the Internet is not allowed

util/user.go
=> fix: If get user home with error, don't display the logs

util/user.go
=> fix: If getting user home with error, don't display the logs

main.go, util/user.go
Add environment `HOME` to service and revert #576 and "fix: If getting user home with error, don't display the logs (#577)".
Also, add config file path to the service only if it is not equal to the default config file path.
This should really fix #575.
Update the description of the service to the latest.
Add it because the environment `HOME` doesn't exist for systemd system service but ddns-go needs it.
Revert #576 and "fix: If getting user home with error, don't display the logs (#577)" because this is no longer an issue.
- [linux - How to use the `$HOME` environment variable in systemd service files - Server Fault](https://serverfault.com/questions/794922/how-to-use-the-home-environment-variable-in-systemd-service-files)
- [Using environment variables in systemd units | Flatcar …
=> fix: add environment HOME to service and revert #576 and #577

README.md, web/writing.html
Add the parameter `desp` because the length limit of the ServerChan `title` is 32.
Optimize the docs for Webhook.
Fix #578.
#578
https://sct.ftqq.com/sendkey
> 参数说明如下：
> - title: 消息标题，必填。最大长度为 32 。
> - desp: 消息内容，选填。支持 [Markdown语法](https://rexxars.github.io/react-markdown/) ，最大长度为 32KB ,消息卡片截取前 30 显示。
=> docs: add parameter `desp` for ServerChan and optimize Webhook

config/config.go
Running commands with Restricted Shell.
The security of Shell is important, so use `bash -r` to limit the commands that the Shell can run.
- [The Restricted Shell (Bash Reference Manual)](https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html)
=> chore: use Restricted Shell

config/config.go
Output standard error (stderr).
#592 no stderr displayed, only `exit status 1`.
https://pkg.go.dev/os/exec#Cmd.CombinedOutput
=> fix(config): output stderr

main.go, util/user.go
- Revert #579
- Fix #602.
In Windows, the `%USERPROFILE%` for normal user and SYSTEM user are different, revert #579 to fix this issue.
Caused by #579.
=> Revert #579

README.md, config/config.go, config/domains.go, config/webhook.go, dns/alidns.go, dns/baidu.go, dns/callback.go, dns/cloudflare.go, dns/dnspod.go, dns/godaddy.go, dns/google_domain.go, dns/huawei.go, dns/index.go, dns/porkbun.go, go.mod, go.sum, main.go, web/basic_auth.go, web/netInterfaces.go, web/save.go, web/webhookTest.go, web/writing.go
=> feat: github.com/jeessy2/ddns-go/v5

.github/dependabot.yml, Dockerfile, go.mod
deps: bump golang from 1.19 to 1.20
=> deps: bump golang from 1.19 to 1.20

.vscode/launch.json, dns/callback.go
remove useless lastIPv4/lastIPv6 in callback
=> fix: remove useless lastIPv4/lastIPv6 in callback

dns/callback.go, dns/godaddy.go, dns/namecheap.go
在callback, godaddy, namecheap 因没有接口查询域名对应IP，把IP改成缓存本地
同 #484
=> fix: If no change with callback/godaddy/namecheap, don't send webhook

config/webhook.go, dns/index.go, util/http_util.go
以前：请求接口失败时
优化为：当状态为更新失败时，进行强制比对。
以前的强制比对有可能失效
=> feat: Force compare when update fails

web/writing.html
清空之前的DnsId，切换配置有可能加载到其它配置的DnsId
=> fix: clear the previous DNS ID when switching configurations

web/writing.html
=> fix: select the saved net interface

.github/workflows/docker-image.yml, .github/workflows/dockerhub-description.yml, README.md
Push the Docker Image to `ghcr.io`.
Closes #641.
Relying on Docker Hub alone is not reliable enough.[^1]
By adding the steps to login to `ghcr.io` and adding the `ghcr.io` image to do this.
Also, replaces text that can be replaced by secret with secret.
[^1]: https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/
=> ci(docker): push to `ghcr.io`

util/net.go, util/net_test.go, web/basic_auth.go
=> feat: log X-Real-IP header

Dockerfile, config/config.go
Only use Bash if it exist, otherwize use sh.
https://github.com/jeessy2/ddns-go/issues/651#issuecomment-1489878461
> 安卓设备中没有bash，无法执行命令获取地址，能否直接运行命令
- https://gist.github.com/miguelmota/ed4ec562b8cd1781e7b20151b37de8a0
- https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory
=> fix: If Bash does not exist, use sh

.github/workflows/docker-image.yml, .github/workflows/release.yml
Make all workflows success in forked repository.
There're two workflows in forked repository that will fail: `docker-image.yml` and `release.yml`.
`docker-image.yml` fails because the secrets it needs does not exist in forked repository. Running it only in the `jeessy2/ddns-go` repository to fix this.
`release.yml` fails because the default `GITHUB_TOKEN` permission is now read-only. Add `contents: write` to fix this.
- https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
- https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
- https://github.com/goreleaser/goreleaser-action#environment-variables
=> ci: success in forked repository

main.go, util/dns.go, util/dns_test.go, util/http_client_util.go
Support for custom DNS server.
- Fix #587 and fix #589.
- Continue with #590.
If the file `/etc/resolv.conf` does not exist for Unix, Go will use `127.0.0.1` or `::1` as the DNS server. Support for custom DNS server to resolve the issue.
- fatedier/frp#700
- golang/go#8877
- v2ray/v2ray-core#1909
- v2fly/v2ray-core#966
- https://gist.github.com/Integralist/8a9cb8924f75ae42487fd877b03360e2
- https://pkg.go.dev/net#Resolver
**The solution may not be good enough, sorry.**
=> feat: custom DNS server

dns/namecheap.go
IPv6 is not supported by Namecheap Dynamic DNS, so the `addUpdateDomainRecords` func will end when `recordType` is AAAA.
#686
Ref: https://www.namecheap.com/support/knowledgebase/article.aspx/29/11/how-to-dynamically-update-the-hosts-ip-with-an-http-request/
> **NOTE**: It is only possible to dynamically update IPv4 addresses (A records) at this time. Currently, IPv6 is not supported by our Dynamic DNS.
=> docs(namecheap): IPv6 is not supported

README.md, main.go, util/ip_cache.go
https://github.com/jeessy2/ddns-go/issues/706
可配置 IP 缓存次数,增加本地IP 检查频率, 且不会被服务商限流
=> feat: ip cache time configable

main.go, util/ip_cache.go
Fix the problem that ip cache time is one less
这个问题不影响功能,可以晚一点合并,看看是否还有其他细节没注意到
=> fix: Fix the problem that ip cache time is one less

config/config.go
Print log when `gettype` is unknown.
No response when `gettype` is unknown.
#717
=> chore(config): print log when `gettype` is unknown

.github/workflows/test.yml, util/open_explorer.go, util/termux.go, util/termux_test.go
Don't execute command on Termux, as Android has a seccomp policy blocking `faccessat2`.
Can be imperfectly fixes #672.
Also build arm64 in the `test` CI.
- #672
- #674
- https://github.com/golang/go/commit/58f6022eee95f43b4e0dc640b012bb3f574898f1
- golang/go#60125
- JanDeDobbeleer/oh-my-posh#3560
- docker/compose#10511
=> fix(open_explorer): don't execute command on Termux

main.go
Add the `-v` flag to output the `ddns-go` version.
Related to Homebrew/homebrew-core#132725.
=> fix: add `-v` flag to output version

dns/index.go, dns/wait_net.go, main.go, util/net.go
No more delay on first run.
Fixes #709.
#709
To do this, make sure the service waits for the network to be ready before starting:
Systemd configures dependencies with `Dependencies`. e.g. https://github.com/kardianos/service/blob/fffe6c52ed0fd8653543bbe72432dbf6ea02f300/example/logging/main.go#L73
Windows uses `DelayedAutoStart` to change the startup type to `自动(延迟启动)` (wait for the `自动` service to finish starting before starting). e.g. https://github.com/Graylog2/collector-sidecar/blob/e10b4c66dc1cc683a2168521fba414bcb855c0da/services/service_options_windows.go#L22
Ref: https://stackoverflow.com/a/25575496
=> feat: no more delay on first run

dns/wait_net.go
Use `util.CreateHTTPClient` to get the URL.
Fixes #736.
Make sure `customDNSResolver` is called.
#736
=> fix(wait_net): use `util.CreateHTTPClient` to get URL

web/writing.html
Hide `DnsID` when `idLabel` is empty.
Fixes #738.
#738
=> chore(web): hide `DnsID` when `idLabel` is empty

.github/workflows/release.yml
Automatically bump Homebrew's ddns-go after release.
Fixes #740.
#740
Ref: https://github.com/Homebrew/actions/tree/master/bump-formulae#usage
> One should use the [Personal Access Token](https://github.com/settings/tokens/new?scopes=public_repo,workflow) for `token` input to this Action, not the default `GITHUB_TOKEN`, because `brew bump-formula-pr` creates a fork of the formula's tap repository (if needed) and then creates a pull request.
Following https://docs.github.com/zh/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository, please enter the [Personal Access Token (`workflow` scope enabled)](https://github.com/settings/tokens/new?scopes=public_repo,workflow) into the secret `HOMEBREW_COMMITTER_TOKEN`.
=> ci(release): add Homebrew

README.md, dns/wait_net.go, util/dns.go, util/dns_test.go, util/http_client_util.go
Set DNS server when err contains loopback server.
Fixes #746.
- #587
- #589
- #590
- #682
- #702
- #746
=> fix: set DNS server when err contains loopback server

config/domains.go, dns/godaddy.go
Using `@` as the name prevents updating all records in the domain if the subdomain is lost.
Fixes #769.
#769
https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName
=> fix(GoDaddy): use `@` as name when subdomain is missing

Dockerfile, config/config.go
No longer running commands with Restricted Shell, as some Shells don't support it.
Determining whether a Restricted Shell is supported may add unnecessary complexity.
Fixes #771.
#771
The following code can be used to fallback when a Restricted Shell is not supported:
```go
// run cmd
out, err := execCmd.CombinedOutput()
str := string(out)
if err != nil && strings.Contains(str, "bash: illegal option -r") {
// 如果不支持受限 Shell 则使用 `bash -c` 运行命令
// https://github.com/jeessy2/ddns-go/issues/771
execCmd = exec.Command("bash", "-c", cmd)
out, err = execCmd.CombinedOutput()
if err != nil {
log.Printf("获取%s结果失败! 未能成功执行命令：%s，错误：%q，退出状态码：%s\n", addrType, execCmd.String(), out, err)
return ""
}
} else {
log.Printf("获取%s结果失败! 未能成功执行命令：%s，错误：%q，退出状态码：%s\n", addrType, execCmd.String(), out, err)
return …
```
=> fix: no more Restricted Shell

.github/ISSUE_TEMPLATE/bug_report.yml, Makefile
Use the HEAD commit as the ddns-go version if the tag is missing.
Also, add more instructions to `bug_report.yml` on how to find the ddns-go version.
Fixes #776.
#776
=> chore: use HEAD commit as version when tag is missing

go.mod, go.sum, web/password.go, web/save.go
Use [go-password-validator](https://github.com/wagslane/go-password-validator) to checks that the password meets the minimum password requirements.
Fixes #778.
#778
https://github.com/wagslane/go-password-validator
https://github.com/coder/coder/blob/0c73164f15da870f0c71d842844a95e4fb73304e/coderd/userpassword/userpassword.go#L128
=> feat(web): validate password

web/writing.html
增加 Namecheap DDNS 不支持更新 IPv6 的说明
=> docs: namecheap don't supports ipv6 ddns

main.go, util/semver/version.go, util/semver/version_test.go, util/update/apply.go, util/update/apply_test.go, util/update/arch.go, util/update/arm.go, util/update/decompress.go, util/update/decompress_test.go, util/update/detect.go, util/update/errors.go, util/update/latest.go, util/update/package.go, util/update/release.go, util/update/update.go
Added packages `update` and `semver` that can be used for selfupdate.
Fixes #595.
#595
Most of the code was copied from [go-selfupdate](https://github.com/creativeprojects/go-selfupdate), [go-update](https://github.com/inconshreveable/go-update) and [semver](https://github.com/Masterminds/semver). Most of the unneeded code has been removed, so there is no need to add new dependencies.
In addition, users with the `mips` arch will not be able to selfupdate, as there is no way to get the float of the MIPS arch.
Tested OS and arch:
=> feat: self update

README.md
Use the new syntax `[!NOTE]` to continue highlighting "Notes".  
The syntax used during the beta testing period is now deprecated and will be removed.
- https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
- https://github.com/orgs/community/discussions/16925#discussioncomment-6506860
=> docs: use new note syntax [skip ci]

main.go, util/http_client_util.go
Set `InsecureSkipVerify` to true for all `http.Transport` only once.
https://github.com/jeessy2/ddns-go/pull/821#issuecomment-1681780798
=> refactor: set `InsecureSkipVerify` only once

config/webhook.go
fix #877
webhook 仅在第三次失败时，才会触发。防止网络异常导致webhook通知过多
=> feat: The webhook is only triggered once after the third failure

main.go
supports restart ddns-go in service
fix: https://github.com/jeessy2/ddns-go/discussions/881
=> feat: supports restart ddns-go in service

Dockerfile
dockerfile 中添加了 grep 和 curl。
有些场景想从路由器的 restful api 拿到公网 IP，添加这两个包便于自定义命令获取内网。
感谢作者搞了个好用的ddns工具。
=> build: add curl&grep

config/domains.go, config/domains_test.go, go.mod, go.sum
Use publicsuffix to parse domain into root domain and sub domain.
Fixes #951.
#951
The [`publicsuffix.EffectiveTLDPlusOne`](https://pkg.go.dev/golang.org/x/net/publicsuffix#EffectiveTLDPlusOne) func does not work properly when the domain has a query string, so the domain is split.
=> refactor(domains): use publicsuffix to parse

util/net.go
for k8s .cluster.local
Motivation
make it good
user always access with "http://ddns-go.default.svc.cluster.local:9876/"
it's private domain
=> opt IsPrivateNetwork func

web/password.go, web/save.go
=> feat: Reduce password strength verification when using on the intranet

web/writing.html
When the same log appears multiple times, using `indexOf` will get the index of the first time, so a new log will always pop up even if there is no new log.
Using `lastIndexOf` will fix this.
---
For example, we have the following logs:
```javascript
const logsList = ["foo", "bar", "bar"];
const oldLogItem = "bar";
```
Using `indexOf`:
```javascript
const newLogsList = logsList.slice(logsList.indexOf(oldLogItem) + 1);
console.log(newLogsList); // 'bar'
```
It will always have a new log.
Using `lastIndexOf`:
```javascript
const newLogsList = logsList.slice(logsList.lastIndexOf(oldLogItem) + 1);
console.log(newLogsList); // []
```
There are no new logs.
The same log may appear multiple times.
HTML is formatted with Prettier, in a separate commit (82cb616).
=> fix(web): correctly display new logs when the same log appear multiple times

dns/cloudflare.go
支持传递自定义参数`comment`来对 cloudflare 的 DNS 记录进行筛选，从而利用不同 comment 实现单域名多 IP 地址的效果
同#923，需要“单域名多 IP”的支持
- 当`comment`参数未指定时，行为和原先一致：忽略 DNS 记录的 comment，只匹配域名，且不会修改 comment
- 如果需要匹配无 comment 的记录，可以传入空串，例如`www:example.cn.eu.org?comment=`
- [API](https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-list-dns-records) 其实还支持`.contains`等更高级的匹配模式，但对于“单域名多 IP”这一目标来说还用不到，因此暂未实现
=> feat(cloudflare): support `comment` param

util/messages.go, util/ordinal.go, util/ordinal_test.go, web/save.go
Logging when both IPv4 and IPv6 domains are not provided.
Fixes #1036 and other similar issues.
Currently, if both IPv4 and IPv6 domains are not provided, nothing happens. In this case, we should log this.
- #899
- #1036
Bool `firstTime` was based on a config error, but the error was ignored. Fixed.
=> fix(web): logging if no domain is entered

static/constant.js
Right now, the help text underneath the domains only states that colons can be used to separate domains, but not in which cases.
Some users don't realize that you can split domains by using colons.
- #1030
- #1014
There may be other words are better than "the domain is unregistrable".
=> docs(domainsHelp): indicate when separated by a colon is needed

config/webhook.go, config/webhook_test.go, util/string.go, web/save.go
Now, function `checkParseHeaders` only works properly if the line break is `\r\n`. Using the `splitLines` function solves this problem.
Fixes #1045
- #1045
Rewritten the function `checkParseHeaders` and renamed it to `extractHeaders` for better readability.
=> refactor(headers): support all types of line breaks

dns/index.go, dns/vercel.go, static/constant.js
Add [vercel](https://vercel.com/) dns support.
我这边测试了下，能跑
=> feat(dns): support vercel dns

README.md, README_EN.md, dns/dynadot.go, dns/index.go, static/constant.js, util/messages.go
增加对Dynadot域名的DDNS支持
我们是Dynadot的开发团队，Dynadot是一家国外域名注册商，目前我们大约管理480w域名并且还在持续增长。近期我们需要一个DDNS的客户端并且能支持跨平台，DDNS-GO是一个非常好的选择，所以我们希望使用DDNS-GO作为我们目前的官方推荐客户端
我在代码中拓展了Dynadot的配置选项，并对封装好的功能做了一些测试工作，包括（域名设置、中英文日志、错误状态日志打印），目前该功能在Dynadot还在我们的灰度测试中，但是测试工作已经基本完成，并且会在合并后发行新版的安装包后将该功能上线。
=> Add support for Dynadot.

dns/cloudflare.go, dns/dnspod.go, dns/google_domain.go, dns/huawei.go, dns/namecheap.go, util/update/detect.go, util/update/package.go, util/update/update.go
Remove unused params and unnecessary nil checks found by `gopls`.
These warnings are too noisy.
The `commonRequest` function in `Dnspod` was renamed to `request` because it was too long.
- https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/unusedparams
- https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness
=> chore: remove unused params and unnecessary nil checks

main.go, util/net_resolver.go, util/wait_internet.go
when local dns error occurs try every dns
improve #1057
=> fix: when local dns error occurs try every dns

.goreleaser.yml
After revisiting the following issues, I finally realized that the `bad system call` bug on Termux should be fixed when GOOS is `android`. 
- golang/go#60125
- golang/go@58f6022eee95f43b4e0dc640b012bb3f574898f1
So, we just need to add a build for Android.
**Test passed on Termux.**
Fixes #1075.
#1075
- mattn/efm-langserver#268
- wormi4ok/evernote2md#109
- twpayne/chezmoi#3508
- #718
=> fix(goreleaser): add build for Android

dns/cloudflare.go, dns/huawei.go, dns/porkbun.go, util/messages.go
Logging only the root domain if the domain is not found in the DNS provider.
Useful when `publicsuffix` provides a wrong root domain.
- #1116 The log doesn't indicate which parts of the domain were used as a root domain.
=> chore(dns): log only the root domain if not found in provider

README.md, README_EN.md, config/config.go, go.mod, go.sum, main.go, static/constant.js, util/bcrypt.go, util/messages.go, web/login.go, web/save.go, web/writing.go, web/writing.html
fix: #1100 #1022 #934 #554
- Encrypt password using bcrypt
- Add reset password function
=> feat: reset password

static/constant.js
fix web godaddy url error
web 界面-英文模式下，godaddy 的 create api key 的链接是 Porkbun
感谢作者的贡献，我另外发现godaddy最近修改api的使用权限，必须拥有50个域名的个人才可以调用域名相关api。
我没想好对此ddns-go需不需要做调整，如何做调整。上述 notes 供作者你参考。
=> fix: web godaddy url error

.goreleaser.yml
Update GoReleaser's config to version 2 in preparation for #1140.
Instructions at https://goreleaser.com/blog/goreleaser-v2/#upgrading have been followed.
- #1140
**No breaking changes during the upgrade process.** So we can just add the `version` header in the configuration file.
=> chore(GoReleaser): update config to version 2

config/webhook.go, dns/callback.go, dns/namecheap.go, dns/namesilo.go
Changed all `ReplaceAll()` to `NewReplacer()` to improve performance when replacing parameters.
Compared to `ReplaceAll()`, `NewReplacer()` is probably a better choice, because you only need to maintain a list of old and new string pairs.
Use a map to build parameters in callback to improve readability.
Also fixed `this value of err is never used (SA4006)` in `NameSilo.listRecords` by error handling.
---
- https://pkg.go.dev/strings#NewReplacer
=> perf(params): use `NewReplacer` to replace params

web/login.html
Use a prompt instead of auto login
fix: #1098
=> fix: Use a prompt instead of auto login

config/domains.go, config/domains_test.go, dns/cloudflare.go
Converts DNS record names to its Punycode format with package [`golang.org/x/net/idna`](https://pkg.go.dev/golang.org/x/net/idna).
Cloudflare API still has trouble handling Unicode forms of IDNs.
- #661
- #1159
- cloudflare/cloudflare-go#688
- cloudflare/cloudflare-go#690
---
Also use [`url.Values`](https://pkg.go.dev/net/url#Values) to build the URL parameters for GET requests.
=> fix(cloudflare): convert DNS record names to Punycode

util/net_resolver.go
为 custom DNS Servers 添加 DNS-over-TCP 查询支持
避免传统 53/udp 端口不可用的情况
1、不添加`udp://`、`tcp://`协议前缀的情况下，默认使用 UDP 协议
2、不添加`:53`端口结构的情况下，默认使用 53 端口
=> feat: add DNS-over-TCP support to customize DNS servers

dns/index.go, dns/traffic_route.go, static/constant.js, util/traffic_route_signer.go
Add volcengine TrafficRoute support
字节旗下火山引擎的域名经常搞[特惠活动](https://www.volcengine.com/activity/domain)，我最近就买了一个，但是ddns还不支持
TrafficRoute 是火山引擎推出的解析调度套件。TrafficRoute 提供了权威 DNS，递归 DNS，私网 DNS 以及全局流量管理功能。TrafficRoute 为您的业务提供了安全，可靠，可定制的域名解析和流量调度服务。
=> Add volcengine TrafficRoute support

main.go, util/andriod_time.go
修复安卓环境运行ddns-go 少8小时的问题。
[go/src/time/zoneinfo_android.go]
func initLocal() {
// TODO(elias.naur): getprop persist.sys.timezone
localLoc = *UTC
}
zoneinfo_android.go 固定了 localLoc 为 UTC，所以设置环境变量无效。
设置启动参数 tZ, 默认从环境获取时区字符串, 判断当前GOOS为 android 调用 FixTimezone 进行时区修正
=> fix: 安卓环境Go Time 固定UTC时区，通过时区获取偏移量修正时区

main.go, static/common.css, static/constant.js, web/logout.go, web/writing.html
=> add logout feature

web/logout.go
=> Fix bug by overwriting existing system cookie

config/webhook.go
This PR fixes an issue with the URL path not being properly escaped when constructing an HTTP request. It updates the code to use u.EscapedPath() instead of u.Path to ensure that special characters in the URL path are correctly escaped.
I want to add a newline character (%0A) to the URL path. In the current implementation (master branch), there is a hacky workaround that uses %250A (where %0A would be expected) to achieve this. This behavior is incorrect and caused by the lack of proper escaping for the path. By switching to u.EscapedPath(), newline characters and other special characters are correctly encoded, eliminating the need for double-encoding workarounds.
None
=> fix: escape URL path to prevent issues with unescaped characters when use webhook

dns/dynv6.go, dns/index.go, static/constant.js
增加对dynv6的支持。支持根域名记录自动更新，子域名记录自动创建/更新，更新时会先对比本地ip和dns服务器记录，如果有变化才会触发更新，避免触发太多webhook。
一直用dynv6，支持ipv6还免费，用callback方式只能更新根域名，为了方便自己和其他dynv6用户，所以增加了支持。
配置：
创建/更新：
ip未变化：
=> add support for dynv6

.github/workflows/release.yml, README.md, README_EN.md
Few people use homebrew to install ddns-go, so we will stop pushing updates to Homebrew to reduce maintenance workload
=> feat: No longer pushing to homebrew

dns/index.go, dns/spaceship.go, static/constant.js
This PR adds support for Spaceship DNS
Spaceship provides really cheap .xyz domains,  and many users rely on their default DNS resolution service.
So it makes sense to include official support in ddns-go.
=> support spaceship dns

README.md, README_EN.md, dns/eranet.go, dns/index.go, dns/nowcn.go, static/constant.js
新增Eranet域名服务商支持
文档补充：更新 README ，添加 Eranet
修复时代互联的ipv6添加失败
增加ddns-go的支持提供商,提高用户使用体验
测试覆盖：ipv4和ipv6均已测试通过,根域名和次级域名也测试通过
依赖影响：无新增第三方依赖，保持项目轻量化
=> feat: 新增Eranet域名服务商支持

config/webhook.go
- # What does this PR do?
When the request path does not have parameters, the request will carry a "?", resulting in service verification failure.  #1559
=> fix: use u.String() to build request URL instead of manual concatenation (#1559)
